name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch: {}

jobs:
  sast-scan:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Run Semgrep SAST
        run: semgrep scan --config auto --error --verbose --exclude=".github"