name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch: {}

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pipeline jalan"